# Generated by Django 4.1.5 on 2024-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
