# Generated by Django 4.1.5 on 2024-04-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='username')),
                ('comment', models.TextField(verbose_name='comment')),
                ('star', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='star')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
